### ISSUE TITLE
C++ standard not specified in CMakeLists.txt

### ISSUE THREAD

**Issue by SchultzC** [udacity/CppND-Capstone-Snake-Game#1]
Had a minor issue building this project.  

Adding the following to CMakeLists.txt solved the issue:
set (CMAKE_CXX_STANDARD 17)

Perhaps just an issue with my default setting but might be worth considering for ease of use.

**Comment by SudKul** [comment]
Hi @SchultzC 
Done in [this commit](https://github.com/udacity/CppND-Capstone-Snake-Game/commit/7d987cf0fa92351f62561e0fe57f51d250ad0f93).
Thank you.
