### ISSUE TITLE
SDL_Error: Couldn't find matching render driver

### ISSUE THREAD

**Issue by flrndttrch** [udacity/CppND-Capstone-Snake-Game#11]
After building the clean and untouched project using:
`cmake .. && make`
I received the following error:
`Renderer could not be created.
SDL_Error: Couldn't find matching render driver`

I ran everything on the provided workspace with GPU enabled in the browser editor. I get the same error in the VS Code Terminal.

Does anyone have an idea what's going on?

Thanks for the feedback!

**Comment by SudKul** [comment]
Hi @flrndttrch 
This looks like a user-specific issue.
You may have to reset the classroom workspace. 
Otherwise, feel free to ask your concern on the Knowledge thread, so that new learners can benefit from the discussion thread there. 
Thank you.
