### ISSUE TITLE
Missing include SDL2 lib; also linker flag is missing

### ISSUE THREAD

**Issue by Horki** [udacity/CppND-Capstone-Snake-Game#2]
scenario 1; not included SDL2 dir;
```
fatal error: SDL.h: No such file or directory
    5 | #include "SDL.h"
      |          ^~~~~~~
compilation terminated.
```

scenario 2; included SDL2 dir but still linker error
```
fatal error: SDL.h: No such file or directory
    5 | #include "SDL.h"
      |          ^~~~~~~
compilation terminated.
```
game.cpp:(.text+0x12a): undefined reference to `SDL_GetTicks'
/usr/bin/ld: game.cpp:(.text+0x149): undefined reference to `SDL_GetTicks'
/usr/bin/ld: game.cpp:(.text+0x1c3): undefined reference to `SDL_GetTicks'
/usr/bin/ld: game.cpp:(.text+0x22f): undefined reference to `SDL_Delay'
/usr/bin/ld: CMakeFiles/SnakeGame.dir/src/controller.cpp.o: in function `Controller::HandleInput(bool&, Snake&) const':
...
```

Fixed by adding to CmakeLists.txt
`
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -I/usr/include/SDL2")`

**Comment by Horki** [comment]
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -I/usr/include/SDL2 -lSDL2")

**Comment by SudKul** [comment]
Hi @Horki 
I am not sure about your underlying OS, and the issue is not reported by all learners.

I'd request you to ask/share your findings on the Knowledge hub so that our mentor network can chime in and newer learners can also benefit from the discussion thread. 
Thank you.
