### ISSUE TITLE
Game::Game random_w & random_h has bug

### ISSUE THREAD

**Issue by derekgui** [udacity/CppND-Capstone-Snake-Game#4]
Your random_w should be 0 to  screen_width/grid_width and random_h should be 0 to 
screen_height/grid_height. Otherwise, you will place food out of screen sometimes.

      random_w(0, static_cast<int>(screen_width/grid_width)),
      random_h(0, static_cast<int>(screen_width/grid_height)

**Comment by SudKul** [comment]
Hi @derekgui 
Thank you, for flagging this issue. 
It has been resolved in this [PR](https://github.com/udacity/CppND-Capstone-Snake-Game/pull/10)
Wishes.
