### ISSUE TITLE
Conan PM: Add SDL2+SDL2_Image

### ISSUE THREAD

**Issue by Horki** [udacity/CppND-Capstone-Snake-Game#6]
For easier maintenance and build, I suggest using "Conan package manager".

https://github.com/Horki/CppND-Capstone-Snake-Game/blob/master/conanfile.txt

https://github.com/Horki/CppND-Capstone-Snake-Game/blob/master/CMakeLists.txt#L11-#L18

**Comment by SudKul** [comment]
Hi @Horki 
Thank you for your suggestion. 
It is your personal opinion to include the Conan package manager, however, we have no such suggestions/requests from our mentor network.
Wishes.
